# Uncomment the next line to define a global platform for your project

target 'MatchupMatchApp' do
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
